# Generated by Django 5.1 on 2024-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='blog_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='imgs'),
        ),
    ]
